spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro

mybatis:
  type-aliases-package: com.springboot.blog.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
